Repository WeBankPartners/wecube-platform, pull requests merged in 2019-11, with the labels that each got.

#488 471 plugin package xml element validation
  platform-core/src/main/java/com/webank/wecube/platform/core/config/SpringAppConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageEntityDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginConfigXmlValidator.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageValidator.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/PluginPackageValidator.java
  platform-core/src/main/java/com/webank/wecube/platform/core/utils/Constants.java
  platform-core/src/main/java/com/webank/wecube/platform/core/utils/StringUtils.java
  platform-core/src/main/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/RegexExampleTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginConfigXmlValidatorTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParserTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
  platform-core/src/test/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/resources/plugin/sample-plugin-config-v2-false.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-v2-false2.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-v2-false3.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-v2-false4.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-v2-false5.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-v2-false6.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-v2.xml
  platform-core/src/test/resources/plugin/sample-plugin-config.xml
  platform-core/src/test/resources/testpackage/service-management-v0.1.zip
Labels: enhancement

#509 #442 fix upload plugin sql issue
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/test/resources/testpackage/service-management-v0.1.zip
Labels: enhancement

#523 475 fix bugs found by test
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginRouteItemService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/DockerContainerManagementService.java
  platform-core/src/main/resources/application.yml
Labels: bug

#536 520 api gateway debugging test
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/common/ApplicationConstants.java
  platform-auth-server/src/main/resources/application.yml
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/ArtifactManagementController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/BatchJobManagementController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/CmdbEnumManagementController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/HomeController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginInstanceController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginRouteItemController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/ResourceDataController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/ResourceManagementController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/SystemVariableController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/UserManagementController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/WorkflowProcessDefinitionController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/WorkflowProcessInstanceController.java
  platform-core/src/main/resources/application.yml
  platform-core/src/main/resources/logback-spring.xml
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/SystemVariableControllerTest.java
  platform-gateway/src/main/java/com/webank/wecube/platform/gateway/controller/DynamicRouteItemController.java
  platform-gateway/src/main/java/com/webank/wecube/platform/gateway/filter/factory/DynamicRouteGatewayFilterFactory.java
  platform-gateway/src/main/java/com/webank/wecube/platform/gateway/route/DynamicRouteConfigurationService.java
  platform-gateway/src/main/resources/application.yml
  wecube-core/pom.xml
Labels: In Progress

#553 #494 update xsd to support isDynamic
  platform-core/src/main/java/com/webank/wecube/platform/core/commons/XPathEvaluator.java
  platform-core/src/main/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/resources/plugin-config-v2.xsd
  platform-core/src/test/resources/plugin/plugin-config-v2.xsd
Labels: enhancement

#557 #494 update entity element as optional
  platform-core/src/main/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginConfigXmlValidatorTest.java
  platform-core/src/test/resources/plugin-config-v2.xsd
  platform-core/src/test/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/resources/plugin/sample-plugin-config-without-data-model-entity.xml
Labels: enhancement

#564 548 fix mac package issue
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginConfigXmlValidatorTest.java
  platform-core/src/test/resources/plugin/sample-plugin-config-cmdb.xml
Labels: bug

#566 560 fix empty data model issue
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
Labels: bug

#568 #560 allow entity to be null in plugin config
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
Labels: bug

#579 494 wecube dynamic model support
  .gitignore
  platform-core/src/main/java/com/webank/wecube/platform/core/commons/ApplicationProperties.java
  platform-core/src/main/java/com/webank/wecube/platform/core/config/SpringAppConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDataModel.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageEntity.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageAttributeDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageDataModelDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageEntityDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageAttributeRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageDataModelRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageEntityRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidator.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageValidator.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/PluginPackageDataModelHelper.java
  platform-core/src/main/resources/application.yml
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParserTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
  platform-core/src/test/resources/application-test.yml
  platform-core/src/test/resources/database/00.drop.all.sql
  platform-core/src/test/resources/database/01.wecube.schema.sql
  platform-core/src/test/resources/plugin-config-v2.xsd
  platform-core/src/test/resources/register-for-parser-test.xml
  platform-core/src/test/resources/testpackage/service-management-v0.1.zip
  wecube-wiki/docs/developer/wecube_developer_guide.md
  wecube-wiki/docs/developer/wecube_developer_guide_en.md
Labels: enhancement

#603 #560 support null entity data model
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidator.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidatorTest.java
  platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity-attribute-without-datatype.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity-but-ref-attribute-name-missing.xml
  platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity.xml
Labels: enhancement

#607 #494 update dev guide
  wecube-wiki/docs/developer/plugin-config-v2.xsd
  wecube-wiki/docs/developer/wecube_developer_package_XML_guide.md
Labels: enhancement

#601 559 fix bugs by monitor plugin debugging test
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginMysqlInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/DockerContainerManagementService.java
  platform-core/src/main/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginConfigXmlValidatorTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/utils/EncryptionUtilsTest.java
  platform-core/src/test/resources/plugin-config-v2.xsd
  platform-core/src/test/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/resources/plugin/sample-plugin-config-null-blocks.xml
  pom.xml
Labels: bug

#614 #559 fix null data model issue
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
Labels: bug

#617 #559 fix data model issue
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/resources/plugin/plugin-config-v2.xsd
Labels: bug

#618 593 plugin actions by entity
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigInterfaceDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigInterfaceParameterDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/handler/GlobalExceptionHandler.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigInterfaceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
Labels: enhancement

#641 #631 fix parameters missing issue after interface enabled
  .circleci/config.yml
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
  pom.xml
Labels: bug

#660 #655 update entity reference for dynamic model
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageEntityDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
Labels: bug

#668 #661 rollback package name regex for now
  platform-core/src/main/java/com/webank/wecube/platform/core/utils/Constants.java
Labels: API tool, enhancement

#674 #672 update data model expression to use GreaterThan instead of Dash …
  platform-core/pom.xml
  platform-core/src/main/antlr4/DataModel.g4
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModel.interp
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModel.tokens
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelBaseListener.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelBaseVisitor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelLexer.interp
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelLexer.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelLexer.tokens
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelListener.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/generated/DataModelVisitor.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/DataModelExpressionServiceTest.java
Labels: bug

#754 Optimize data deconstruction
  wecube-portal/src/api/base.js
Labels: bug

#793 #791 allow null description for entity and attribute in datamodel
  platform-core/pom.xml
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageAttributeRepositoryTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageEntityRepositoryTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidatorTest.java
  platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity-attribute-without-description.xml
Labels: enhancement

#799 #738 throw exception if required parameter not set for plugin
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigInterfaceParameterDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
Labels: bug
