Repository WeBankPartners/wecube-platform, pull requests merged in 2019-10, with the labels that each got.

#251 132 wecube datamodel overview
  wecube-core/src/main/java/com/webank/wecube/core/controller/PluginPackageDataModelController.java
  wecube-core/src/main/java/com/webank/wecube/core/domain/plugin/PluginPackageAttribute.java
  wecube-core/src/main/java/com/webank/wecube/core/domain/plugin/PluginPackageEntity.java
  wecube-core/src/main/java/com/webank/wecube/core/dto/PluginPackageAttributeDto.java
  wecube-core/src/main/java/com/webank/wecube/core/dto/PluginPackageEntityDto.java
  wecube-core/src/main/java/com/webank/wecube/core/jpa/PluginPackageAttributeRepository.java
  wecube-core/src/main/java/com/webank/wecube/core/jpa/PluginPackageEntityRepository.java
  wecube-core/src/main/java/com/webank/wecube/core/jpa/PluginPackageRepository.java
  wecube-core/src/main/java/com/webank/wecube/core/service/PluginPackageDataModelService.java
  wecube-core/src/main/java/com/webank/wecube/core/service/PluginPackageDataModelServiceImpl.java
  wecube-core/src/main/java/com/webank/wecube/core/utils/constant/DataModelDataType.java
  wecube-core/src/main/java/com/webank/wecube/core/utils/constant/DataModelState.java
  wecube-core/src/main/resources/database/01.wecube.schema.sql
  wecube-core/src/test/java/com/webank/wecube/core/controller/PluginPackageDataModelControllerTest.java
  wecube-core/src/test/java/com/webank/wecube/core/jpa/PluginRepositoryIntegrationTest.java
  wecube-core/src/test/java/com/webank/wecube/core/service/PluginPackageDataModelServiceTest.java
  wecube-core/src/test/resources/database/01.wecube.schema.sql
Labels: Dont Merge

#431 429 plugin package config and data model persistence
  platform-core/pom.xml
  platform-core/src/main/java/com/webank/wecube/platform/core/config/S3ClientConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/JsonResponse.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/SystemVariable.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigFilteringRule.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterfaceParameter.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAttribute.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAuthority.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDependency.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesDocker.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesMysql.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesS3.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageEntityDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigCopyHelper.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/S3Client.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/BaseSpringBootTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/DatabaseBasedTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/AbstractControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
  platform-core/src/test/resources/application-test.yml
  platform-core/src/test/resources/database/00.drop.all.sql
  platform-core/src/test/resources/database/01.wecube.schema.sql
  platform-core/src/test/resources/plugin-config-v2.xsd
  platform-core/src/test/resources/register-for-parser-test.xml
  platform-core/src/test/resources/testpackage/service-manage-v0.1.zip
  pom.xml
Labels: enhancement

#455 454 update en doc
  wecube-wiki/docs/developer/wecube_developer_guide_en.md
  wecube-wiki/docs/install/wecube_compile_guide_en.md
  wecube-wiki/docs/install/wecube_install_guide_en.md
Labels: documentation

#466 437 resource file handling
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageResourceFile.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageResourceFilesDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageResourceFileRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageResourceFileService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
  platform-core/src/test/resources/database/01.wecube.schema.sql
Labels: enhancement

#480 442 fix bugs
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDependency.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageResourceFile.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageResourceFilesDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageResourceFileRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/UserManagerService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageResourceFileService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
  platform-core/src/test/resources/database/01.wecube.schema.sql
Labels: enhancement

#485 #442 fix ui exists logic
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageRepositoryTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageResourceFileRepositoryTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
  platform-core/src/test/resources/database/01.wecube.schema.sql
Labels: enhancement
