Repository WeBankPartners/wecube-platform, pull requests merged in 2019-12, with the labels that each got.

#838 #746 merge menus for packages with multiple version
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/MenuItem.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/MenuItemDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/MenuService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/main/resources/logback-spring.xml
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepositoryTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/MenuServiceTest.java
  platform-gateway/src/main/resources/logback-spring.xml
Labels: bug

#888 #887 fix id with spaces
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
Labels: bug

#891 #887 fix id with spaces
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/MenuItem.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/ResourceItem.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/ResourceServer.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/SystemVariable.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterfaceParameter.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginMysqlInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAttribute.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAuthority.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDataModel.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDependency.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageEntity.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesDocker.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesMysql.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesS3.java
Labels: bug

#894 #887 fix id with spaces
  platform-core/src/main/java/com/webank/wecube/platform/core/utils/Constants.java
  platform-core/src/main/resources/database/02.wecube.system.data.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/SystemVariableServiceTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/UserManagementServiceTest.java
  platform-core/src/test/resources/database/03.wecube.test.data.sql
Labels: bug

#909 #845 state control fix for plugins and services
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginInstanceController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginMysqlInstanceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginConfigServiceTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginPackageServiceTest.java
Labels: bug

#968 962 Upgrade bpmn-js configuration
  wecube-portal/src/pages/collaboration/workflow-orchestration.vue
Labels: enhancement

#970 876 add role if not exists in system
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginPackageServiceMockTest.java
Labels: enhancement

#1005 #783 filter plugin services by entity name
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
Labels: bug

#1008 #783 filter plugin services by entity name and null entity name as well
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigInterfaceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
Labels: bug

#1026 1019 get all plugin interfaces without entity name when filtering by entity
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigInterfaceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
Labels: bug

#1027 #990 pick up running instances for active package only
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginInstanceServiceTest.java
Labels: bug

#1037 #1036 Bug fix
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: enhancement

#1044 928 segregate system domain and plugin domain
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/MenuItem.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/ResourceItem.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/ResourceServer.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/SystemVariable.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterfaceParameter.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginMysqlInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAttribute.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAuthority.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDataModel.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDependency.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageEntity.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesDocker.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesMysql.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesS3.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigInterfaceParameterDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/SystemVariableDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigInterfaceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageEntityRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/SystemVariableRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/SystemVariableService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/PluginInvocationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/DomainIdBuilder.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/main/resources/database/02.wecube.system.data.sql
  platform-core/src/main/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/SystemVariableControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParserTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/SystemVariableServiceTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginConfigServiceTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/support/DomainIdBuilderTest.java
  platform-core/src/test/resources/database/03.wecube.test.data.sql
  platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity-attribute-without-description.xml
  platform-core/src/test/resources/register-for-parser-test.xml
  platform-core/src/test/resources/testpackage/servicemanagement-v0.1.zip
Labels: Dont Merge

#1047 #1046 system variables not showed up fix
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
Labels: bug

#1073 1072 upgrade plugin management
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: enhancement

#1081 #1080 fix plugin config save issue
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageEntityRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
Labels: bug

#1086 1080 fix dev
  .gitignore
  README.md
  README_CN.md
  README_EN.md
  platform-core/pom.xml
Labels: bug

#1141 #1103 keep package status unchanged after new data model applied
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
Labels: enhancement

#1142 #1010 menu to support chinese and english
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/MenuItem.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDependency.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/MenuItemDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/main/resources/database/02.wecube.system.data.sql
  platform-core/src/main/resources/plugin/plugin-config-v2.xsd
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParserTest.java
  platform-core/src/test/resources/database/03.wecube.test.data.sql
  platform-core/src/test/resources/plugin/sample-plugin-config-v2.xml
  platform-core/src/test/resources/register-for-parser-test.xml
Labels: enhancement

#1160 #1116 plugin menu to support status
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginInstance.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenuStatusListener.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/MenuItemDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/ResourceDataQueryService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/user/RoleMenuServiceImpl.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepositoryTest.java
Labels: enhancement

#1161 #1116 fix status issue
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenuStatusListener.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/MenuItemDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepository.java
  platform-core/src/main/resources/database/01.wecube.schema.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepositoryTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepositoryTest.java
Labels: bug

#1189 #1188 adding error message for overview task node execution
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/workflow/TaskNodeExecContextDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/AbstractPluginInvocationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowProcInstService.java
Labels: enhancement

#1213 #1210 Bug fix
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: bug

#1217 #1095_Bug_fix
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: enhancement

#1224 #1220 Enhance workflow excution
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement
