Repository WeBankPartners/wecube-platform, pull requests merged in 2020-05, with the labels that each got.

#1731 1402 multi options as result
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/controller/ApplicationInformationController.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/AuthorityManagementService.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/RoleManagementService.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/SubSystemManagementService.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/UserManagementService.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/impl/SubSystemInfoDataServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/model/workflow/GraphNode.java
  platform-core/src/main/java/com/webank/wecube/platform/core/model/workflow/PluginInvocationCommand.java
  platform-core/src/main/java/com/webank/wecube/platform/core/model/workflow/PluginInvocationResult.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/ApplicationInformationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/dme/EntityDataRouteFactory.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/dme/EntityRouteDescription.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/dme/StandardEntityOperationRestClient.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/AbstractPluginInvocationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/AsyncPluginInvocationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/InVmServiceInvocationEventResolver.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/PluginInvocationProcessor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/PluginInvocationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowEngineService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowProcDefService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowProcInstService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/RestClient.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/authserver/AbstractAuthServerRestClient.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/authserver/AuthServerRestClientProperties.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/plugin/PluginInvocationRestClient.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/plugin/dto/PluginRequest.java
  platform-core/src/main/resources/application.yml
  platform-core/src/main/resources/database/03.wecube.flow_engine.schema.sql
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/WorkflowConstants.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/delegate/AbstractServiceExceptionHandleDelegate.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/delegate/PlugableApplicationTaskDispatcher.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/model/ServiceInvocationEvent.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/model/ServiceInvocationEventImpl.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/AbstractServiceNodeEndListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/AbstractServiceNodeStartListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/BpmnProcessModelCustomizer.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/CustomBpmnParse.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/ProcessInstanceEndListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/ProcessInstanceStartListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/ServiceTaskEndListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/ServiceTaskStartListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/SpringApplicationContextUtil.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/SubProcessEndListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/SubProcessStartListener.java
  platform-workflow/src/main/java/com/webank/wecube/platform/workflow/parse/UserTaskEndListener.java
Labels: Dont Merge

#1742 #1737 Fix bug
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1755 1520 um adapter
  platform-auth-server/pom.xml
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/authentication/AuthenticationChecker.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/authentication/CompositeAuthenticationProvider.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/authentication/UmAuthenticationChecker.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/config/AuthSecurityConfigurerAdapter.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/config/AuthServerProperties.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/controller/LocalSubSystemManagementController.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/dto/SimpleLocalUserDto.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/dto/SubSystemTokenDto.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/entity/SysUserEntity.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/filter/DefaultJwtBuilder.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/filter/JwtBuilder.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/filter/JwtSsoBasedAuthenticationFilter.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/filter/JwtSsoBasedLoginFilter.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/filter/JwtSsoBasedRefreshTokenFilter.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/handler/Http401AuthenticationEntryPoint.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/handler/Http403AccessDeniedHandler.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/handler/JwtSsoBasedAuthenticationFailureHandler.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/model/AuthContext.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/model/SysUser.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/model/UmAuthContext.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/SubSystemManagementService.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/UserManagementService.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/impl/LocalUserServiceImpl.java
  platform-auth-server/src/main/resources/database/01.auth.schema.sql
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/user/UserDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/dme/StandardEntityOperationRestClient.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/user/UserManagementServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowEngineService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowProcInstService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/authserver/AsUserDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/plugin/PluginInvocationRestClient.java
Labels: Dont Merge

#1783 #1781 add security control
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/config/WebSecurityConfig.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/controller/LocalSubSystemManagementController.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/dto/SimpleSubSystemDto.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/http/filter/JwtSsoBasedAuthenticationFilter.java
  platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/SubSystemManagementService.java
Labels: Dont Merge

#1788 #1787 Update table column header display
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement
