Repository WeBankPartners/wecube-platform, pull requests merged in 2020-01, with the labels that each got.

#1225 1220 enhance workflow execution
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1232 #1220 enhance workflow execution
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1233 #1220 Update graph label
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1236 #1235 Bug fix
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1240 #1239 Empty canvas when switching buttons
  wecube-portal/src/pages/implementation/batch-execution.vue
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1254 #1274 Enhance history workflow
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1283 #1281 Upgrade plugin register
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: enhancement

#1291 #1289 Fix bug
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: bug

#1294 #1284 Adaptive font size for workflow
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1296 #1277 Fix bug
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1302 #1277 Fix bug
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1306 #1229 Fix bug
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: bug

#1317 #1308 zoom modal
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1327 1326 Bug fix
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: bug

#1334 #1325 Bug fix
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: bug

#1335 1308 upgrade workflow exection
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1322 1237 ticket report supporting
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/workflow/StartProcInstRequestDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/entity/event/OperationEventEntity.java
  platform-core/src/main/java/com/webank/wecube/platform/core/job/OperationEventJobsHandler.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/event/OperationEventRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/workflow/ProcDefInfoRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/model/workflow/WorkflowNotifyEvent.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/event/OperationEventProcStarter.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/event/OperationEventsExecutor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/PluginInvocationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowProcDefService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowProcInstEndEventNotifier.java
Labels: Dont Merge

#1343 #1342 Bug fix
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: bug

#1347 #1346 Workflow node display
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1348 1201 batch execution i18n
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1358 1356 enhance batch exection
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement
