Repository WeBankPartners/wecube-platform, pull requests merged in 2020-07, with the labels that each got.

#1863 1853 batch exec refactor
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/workflow/WorkflowProcessInstanceController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/BatchExecutionJob.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/ExecutionJob.java
  platform-core/src/main/java/com/webank/wecube/platform/core/domain/ExecutionJobParameter.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/DmeFilterDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/DmeLinkFilterDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/Filter.java
  platform-core/src/main/java/com/webank/wecube/platform/core/model/datamodel/DataModelExpressionToRootData.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/DataModelExpressionListener.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/DataModelExpressionParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModel.interp
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModel.tokens
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelBaseListener.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelBaseVisitor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelLexer.interp
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelLexer.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelLexer.tokens
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelListener.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelParser.java
  platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/antlr4/DataModelVisitor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/BatchExecutionService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/datamodel/ExpressionService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/datamodel/ExpressionServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/datamodel/NonExpressionServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/datamodel/RootlessExpressionServiceImpl.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/dme/EntityQueryExecutor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/dme/StandardEntityOperationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/dme/StandardEntityQueryExecutor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginArtifactOperationExecutor.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/DataModelServiceStub.java
  platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/dto/DataModelExpressionDto.java
  platform-core/src/main/resources/DataModel.g4
  platform-core/src/main/resources/logback-spring.xml
  platform-core/src/test/java/com/webank/wecube/platform/core/parser/DataModelExpressionParserTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/datamodel/RootlessExpressionServiceMocker.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/datamodel/RootlessExpressionServiceTest.java
  platform-core/src/test/resources/logback-test-spring.xml
Labels: Dont Merge

#1879 #1876 Add tip for batch exection
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1880 1858 plugin auth enhancement
  platform-core/src/main/java/com/webank/wecube/platform/core/controller/plugin/PluginConfigController.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigRoleRequestDto.java
  platform-core/src/main/java/com/webank/wecube/platform/core/entity/PluginAuthEntity.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginAuthRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/jpa/SystemVariableRepository.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/SystemVariableService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigMigrationService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/xmltype/PluginConfigType.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/xmltype/PluginPackageType.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/xmltype/PluginRoleBindingType.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/xmltype/PluginRoleBindingsType.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/xmltype/SystemParameterType.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/xmltype/SystemParametersType.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/ResourceDataQueryService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowProcDefService.java
  platform-core/src/main/java/com/webank/wecube/platform/core/utils/CollectionUtils.java
  platform-core/src/main/resources/application.yml
  platform-core/src/main/resources/db/create/01.wecube.mysql.create.schema.sql
  platform-core/src/main/resources/db/drop/01.wecube.mysql.drop.sql
  platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginConfigServiceTest.java
  platform-core/src/test/java/com/webank/wecube/platform/core/utils/CollectionUtilsTest.java
  platform-core/src/test/resources/logback-test-spring.xml
  platform-gateway/src/main/resources/logback-spring.xml
Labels: Dont Merge

#1888 1876 enhance workflow execution
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1892 #1819 Enhance permission setting
  wecube-portal/src/pages/collaboration/workflow-orchestration.vue
Labels: enhancement

#1906 #1905 Enhance target path display
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1909 #1907 Bug fix
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug
