Repository WeBankPartners/wecube-platform, pull requests merged in 2020-03, with the labels that each got.

#1511 1510 allow user specified bucket name
  build/deploy_generate_compose.sh
  build/docker-compose.tpl
  build/platform-core/start_platform_core.sh
  build/wecube.cfg
  platform-core/src/main/resources/database/02.wecube.system.data.sql
Labels: Dont Merge

#1515 #1514 Fix bug
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1519 1505 cache batch execution information
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/collaboration/workflow-orchestration.vue
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1522 #1516 Add selectAll for node data
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1524 1518 update plugin data
  wecube-portal/src/pages/collaboration/workflow-orchestration.vue
  wecube-portal/src/pages/components/path-exp.vue
Labels: enhancement

#1526 #1525 Owner role cannot empty
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/collaboration/workflow-orchestration.vue
Labels: enhancement

#1531 #1523 Filter execute result
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1541 1512 batch execution management
  wecube-portal/src/api/server.js
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1543 1512 batch execution management
  wecube-portal/src/locale/i18n/en-US.json
  wecube-portal/src/locale/i18n/zh-CN.json
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: enhancement

#1568 #1567 Fix bug
  wecube-portal/src/pages/collaboration/workflow-orchestration.vue
Labels: bug

#1602 #1596 Fixed bug
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: bug

#1617 #1616 Bread crumb enhance
  wecube-portal/src/main.js
  wecube-portal/src/pages/index.vue
Labels: enhancement
