Repository WeBankPartners/wecube-platform, pull requests merged in 2020-02, with the labels that each got.

#1391 #1311 fix config missing issue
  build/docker-compose.tpl
  build/platform-core/start_platform_core.sh
  platform-core/src/main/resources/application.yml
Labels: Dont Merge

#1393 #1383 Optimize export
  wecube-portal/src/api/base.js
  wecube-portal/src/const/export-file.js
Labels: enhancement

#1431 #1418 Clear workflow-exection cache
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: bug

#1446 #1418 Bug fix for node data display
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: bug

#1466 #1462 Fix bug
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1469 #1445 Add log to workflow-execution
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1478 #1477 Fix bug
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1476 #1474 Enhance workflow data echo
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1479 #1477 Add panel control
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: enhancement

#1488 #1484 Modify node info display
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1489 #1417 Fix bug
  wecube-portal/src/pages/collaboration/components/plugin-register.vue
Labels: bug

#1504 1491 add node data search
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement
