Repository WeBankPartners/wecube-platform, pull requests merged in 2020-04, with the labels that each got.

#1642 #1639 Fixed bug
  wecube-portal/src/pages/implementation/batch-execution.vue
Labels: bug

#1686 #1674 Fix bug
  wecube-portal/src/pages/implementation/workflow-execution.vue
Labels: enhancement

#1706 #1695 - transfer to UTF-8
  platform-auth-server/src/main/resources/database/02.auth.data.sql
Labels: SQL change
